reg_data = TAFFY(
	[{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":43.8},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":64.9},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":49.5},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":52.3},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":56.3},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":60.3},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":27.1},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":31.8},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":35.7},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":41.9},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":42.6},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":46.8},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":35.9},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":56.1},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":56.8},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":42.3},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":45.9},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":63.6},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":18.8},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":31.9},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":35.7},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":26.1},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":27.2},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":40.8},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":43.6},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":46.8},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":50.0},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":53.3},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":56.8},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":60.8},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":21.7},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":26.3},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":30.5},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":34.5},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":38.4},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":43.9},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":43.7},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":42.2},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":48.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":53.3},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":59.5},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":65.9},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":16.6},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":18.8},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":22.6},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":28.2},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":33.5},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":40.7},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":43.0},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":45.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":48.8},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":51.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":54.5},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":58.0},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":22.2},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":25.9},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":29.9},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":33.2},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":36.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":40.5},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":49.0},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":51.2},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":55.4},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":60.1},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":63.6},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":66.0},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":20.4},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":23.7},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":27.2},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":31.8},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":35.6},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":40.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":43.2},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":45.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":48.4},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":51.0},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":54.1},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":59.1},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":21.6},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":25.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":29.6},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":32.7},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":35.3},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":39.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":43.1},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":46.3},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":49.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":52.4},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":55.8},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":59.8},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":26.6},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":32.9},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":37.7},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":41.7},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":45.2},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":49.4},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":38.6},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":41.9},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":45.1},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":47.6},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":51.9},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":56.1},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":23.5},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":28.2},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":32.5},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":35.9},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":39.1},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":43.0},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":42.4},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":45.1},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":48.7},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":50.0},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":55.7},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":60.2},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":28.4},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":33.6},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":34.4},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":42.1},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":46.2},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":50.4},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":39.7},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":42.2},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":44.0},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":46.6},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":51.6},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":55.0},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":23.5},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":26.9},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":29.8},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":33.0},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":36.3},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":40.8},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":35.2},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":37.6},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":40.0},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":42.0},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":44.8},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":49.0},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":26.7},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":30.3},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":33.5},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":36.6},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":34.8},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":43.1},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":38.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":42.4},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":46.8},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":48.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":54.2},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":58.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":19.6},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":24.1},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":28.4},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":32.5},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":36.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":42.8},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":41.1},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":44.3},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":47.3},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":49.2},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":53.8},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":58.1},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":16.2},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":20.8},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":24.0},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":26.9},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":30.4},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":35.4},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":29.8},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":32.4},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":34.4},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":36.0},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":38.9},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":42.7},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":20.7},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":24.5},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":27.4},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":29.9},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":32.4},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":36.2},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":25.7},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":27.5},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":29.6},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":31.4},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":35.0},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":40.6},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":18.3},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":21.6},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":24.5},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":26.7},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":29.5},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":34.1},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":30.7},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":33.1},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":35.7},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":39.4},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":43.4},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":44.6},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":19.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":23.7},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":27.0},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":29.9},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":32.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":36.4},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":26.5},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":28.5},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":29.4},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":31.1},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":35.3},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":39.8},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":15.9},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":18.8},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":21.2},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":23.5},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":26.2},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":31.2},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":26.8},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":29.6},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":31.6},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":33.7},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":36.6},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":40.7},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":19.4},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":23.6},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":25.8},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":27.9},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":30.5},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":34.8},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2012,"mercato":"mercato_lib","value":28.9},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2013,"mercato":"mercato_lib","value":32.5},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2014,"mercato":"mercato_lib","value":35.3},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2015,"mercato":"mercato_lib","value":36.6},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2016,"mercato":"mercato_lib","value":38.9},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2017,"mercato":"mercato_lib","value":42.9},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2012,"mercato":"mercato_lib","value":18.7},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2013,"mercato":"mercato_lib","value":21.8},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2014,"mercato":"mercato_lib","value":23.6},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2015,"mercato":"mercato_lib","value":25.4},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2016,"mercato":"mercato_lib","value":26.9},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2017,"mercato":"mercato_lib","value":29.6},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":56.0},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":34.8},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":49.9},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":47.2},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":43.2},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":39.2},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":72.9},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":68.2},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":64.3},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":58.1},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":57.4},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":53.2},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":63.8},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":43.7},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":42.7},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":57.4},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":53.7},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":36.1},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":81.2},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":68.1},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":64.3},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":73.9},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":72.8},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":59.2},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":55.4},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":52.3},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":49.1},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":45.6},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":42.3},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":38.5},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":78.3},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":73.7},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":69.5},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":65.5},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":61.6},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":56.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":56.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":57.7},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":51.7},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":46.6},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":40.3},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":34.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":83.4},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":81.2},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":77.4},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":71.8},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":66.5},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":59.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":56.7},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":54.2},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":50.7},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":48.2},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":45.2},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":40.9},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":77.8},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":74.1},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":70.1},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":66.8},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":63.7},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":59.5},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":50.2},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":48.4},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":44.1},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":39.4},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":36.0},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":32.5},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":79.6},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":76.3},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":72.8},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":68.2},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":64.4},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":59.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":56.4},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":54.1},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":51.1},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":48.2},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":45.4},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":40.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":78.4},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":74.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":70.4},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":67.3},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":64.7},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":60.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":56.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":53.2},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":49.9},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":47.0},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":43.8},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":39.8},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":73.4},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":67.1},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":62.3},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":58.3},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":54.8},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":50.6},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":59.8},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":56.7},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":53.8},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":50.9},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":47.1},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":42.9},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":76.5},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":71.8},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":67.5},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":64.1},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":60.9},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":57.0},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":56.6},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":54.8},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":50.6},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":47.3},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":43.5},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":38.6},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":71.6},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":66.4},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":65.6},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":57.9},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":53.8},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":49.6},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":59.5},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":57.2},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":55.5},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":52.0},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":47.8},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":44.0},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":76.5},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":73.1},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":70.2},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":67.0},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":63.7},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":59.2},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":63.9},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":61.6},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":59.3},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":56.3},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":54.2},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":50.1},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":73.3},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":69.7},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":66.5},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":63.4},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":65.2},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":56.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":59.5},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":56.1},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":52.3},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":49.5},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":45.1},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":39.3},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":80.4},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":75.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":71.6},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":67.5},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":63.1},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":57.2},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":57.8},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":54.1},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":51.8},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":49.1},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":45.3},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":41.3},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":83.8},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":79.2},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":76.0},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":73.1},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":69.6},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":64.6},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":68.6},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":66.2},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":64.3},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":62.2},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":59.4},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":55.1},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":79.3},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":75.5},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":72.6},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":70.1},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":67.6},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":63.8},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":73.3},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":71.5},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":69.1},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":67.1},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":63.7},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":58.6},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":81.7},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":78.4},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":75.5},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":73.3},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":70.5},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":65.9},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":68.3},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":66.3},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":63.5},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":59.6},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":55.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":53.6},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":80.2},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":76.3},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":73.0},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":70.1},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":67.2},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":63.6},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":71.8},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":70.1},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":69.0},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":66.5},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":62.7},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":57.2},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":84.1},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":81.2},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":78.8},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":76.5},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":73.8},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":68.8},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":71.9},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":69.3},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":67.3},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":64.9},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":62.1},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":56.7},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":80.6},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":76.4},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":74.2},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":72.1},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":69.5},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":65.2},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2012,"mercato":"magg_tutela","value":69.9},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2013,"mercato":"magg_tutela","value":66.5},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2014,"mercato":"magg_tutela","value":63.7},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2015,"mercato":"magg_tutela","value":61.8},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2016,"mercato":"magg_tutela","value":60.0},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2017,"mercato":"magg_tutela","value":55.6},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2012,"mercato":"magg_tutela","value":81.3},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2013,"mercato":"magg_tutela","value":78.2},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2014,"mercato":"magg_tutela","value":76.4},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2015,"mercato":"magg_tutela","value":74.6},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2016,"mercato":"magg_tutela","value":73.1},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2017,"mercato":"magg_tutela","value":70.4},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.2},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.2},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.7},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.2},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.2},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.7},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.4},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.5},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":2.7},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.2},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.7},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.4},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.7},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.8},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.7},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.4},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":1.3},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.8},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":1.7},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":2.2},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":1.2},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.5},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":1.3},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.8},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.4},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":2.4},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":2.1},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":3.0},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.3},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.4},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":1.3},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":2.6},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2012,"mercato":"salvaguardia","value":1.3},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2013,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2014,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2015,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2016,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2017,"mercato":"salvaguardia","value":1.6},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":35.7},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":63.3},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":1.0},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":52.2},
	{"id":"IT-65","nome_reg":"Abruzzo","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":47.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":49.0},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":50.0},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":59.8},
	{"id":"IT-77","nome_reg":"Basilicata","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":40.2},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":52.5},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":45.3},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":2.2},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":63.4},
	{"id":"IT-78","nome_reg":"Calabria","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":36.6},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":51.1},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":47.8},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":1.1},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":59.7},
	{"id":"IT-72","nome_reg":"Campania","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":40.3},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":36.6},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":63.1},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":46.5},
	{"id":"IT-45","nome_reg":"Emilia-Romagna","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":53.5},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":31.7},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":67.8},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.5},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":56.1},
	{"id":"IT-36","nome_reg":"Friuli-Venezia Giulia","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":43.9},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":45.7},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":53.4},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":53.0},
	{"id":"IT-62","nome_reg":"Lazio","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":47.0},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":38.5},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":61.1},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.4},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":57.1},
	{"id":"IT-42","nome_reg":"Liguria","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":42.9},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":34.8},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":64.6},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":51.3},
	{"id":"IT-25","nome_reg":"Lombardia","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":48.7},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":39.3},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":60.1},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.6},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":54.5},
	{"id":"IT-57","nome_reg":"Marche","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":45.5},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":39.7},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":59.0},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":1.4},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":59.9},
	{"id":"IT-67","nome_reg":"Molise","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":40.1},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":35.4},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":64.3},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":48.9},
	{"id":"IT-21","nome_reg":"Piemonte","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":51.1},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":52.8},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":46.4},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":61.0},
	{"id":"IT-75","nome_reg":"Puglia","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":39.0},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":51.3},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":47.8},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.9},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":66.2},
	{"id":"IT-88","nome_reg":"Sardegna","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":33.8},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":51.6},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":46.9},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":1.4},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":59.4},
	{"id":"IT-82","nome_reg":"Sicilia","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":40.6},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":39.0},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":60.2},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.8},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":52.1},
	{"id":"IT-52","nome_reg":"Toscana","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":47.9},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":28.9},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":71.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":51.8},
	{"id":"IT-32","nome_reg":"Trentino-Alto Adige","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":48.2},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":35.4},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":63.9},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.7},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":43.7},
	{"id":"IT-55","nome_reg":"Umbria","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":56.3},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":30.4},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":69.5},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.1},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":50.8},
	{"id":"IT-23","nome_reg":"Valle d'Aosta","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":49.2},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2018,"mercato":"magg_tutela","value":37.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2018,"mercato":"mercato_lib","value":62.4},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_altri","anno":2018,"mercato":"salvaguardia","value":0.3},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2018,"mercato":"magg_tutela","value":55.1},
	{"id":"IT-34","nome_reg":"Veneto","tip_cliente":"bt_dom","anno":2018,"mercato":"mercato_lib","value":44.9}])
